Uhealth/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^myapp/',include('myapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

myapp/urls.py
from django.conf.urls import url
from myapp import views
# SET THE NAMESPACE!
app_name = 'myapp'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^upload/$',views.upload,name='upload'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
def __str__(self):
    return self.user.username

myapp/forms.py
from django import forms
from myapp.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

myapp/views.py
from django.shortcuts import render
from myapp.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

import openpyxl
import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

error={'box_error':[]}

def index(request):
    return render(request,'myapp/index.html')
    

def upload(request):
    if "GET" == request.method:
        return render(request, 'myapp/upload.html', {})
    else:
        excel_file = request.FILES["excel_file"]

        # you may put validations here to check extension or file size

        wb = openpyxl.load_workbook(excel_file)

        # getting all sheets
        sheets = wb.sheetnames
        print(sheets)

        # getting a particular sheet
        worksheet = wb["Sheet1"]
        print(worksheet)

        # getting active sheet
        active_sheet = wb.active
        print(active_sheet)

        # reading a cell
        print(worksheet["A1"].value)

        excel_data = list()
        # iterating over the rows and
        # getting value from each cell in row
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
                print(cell.value)
            excel_data.append(row_data)

        
        error['box_error'].clear()
        context = data_processing_box(excel_data)
        #context.append(data_processing_box(excel_data))
        #context.append(data_processing_pie(excel_data))
        
        
        return render(request, 'myapp/upload.html', {'context':json.dumps(context),'error':json.dumps(error)})
    #return render(request,'myapp/upload.html')


def data_processing_box(excel_data):

    #存title
    title = excel_data[0]
    data = excel_data.copy()
    del data[0]
    #轉float
    df = pd.DataFrame(data, columns=title, dtype='float64')
    #設定會傳入做四分位數的title名稱
    title_list = ['HEIGHT', 'WEIGHT', 'PULSE', 'BLP', 'BHP', 'TC', 'TG', 'BUN', 'CREA', 'GOT', 'GPT']
    context=[]
    for num in range(len(title)):
        title[num] = str.upper(title[num])
        if title[num] in title_list:
            try:
                count = np.sum(df[title[num]].values == "None")
                #print(count)
                df[title[num]] = df[title[num]].replace('None',"")
                df[title[num]] = pd.to_numeric(df[title[num]], errors='ignore')
                tmp = {}
                tmp['title'] = title[num]
                tmp['Q'] = []
                tmp['Q'].append(df[title[num]].quantile(0))
                tmp['Q'].append(df[title[num]].quantile(0.25))
                tmp['Q'].append(df[title[num]].quantile(0.5))
                tmp['Q'].append(df[title[num]].quantile(0.75))
                tmp['Q'].append(df[title[num]].quantile(1))
                tmp['sum']= str(len(df[title[num]])-count)
                context.append(tmp)
            except:
                #print(title[num],'None')
                error['box_error'].append(title[num])
    print(context)
    return context


@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'myapp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'myapp/login.html', {})

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Uhealth</title>
    {% block head_block %}
    {% endblock %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Uhealth</a></li>
          <!--<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>-->
          <li><a class="navbar-link" href="{% url 'myapp:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'myapp:upload' %}">upload</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'myapp:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/myapp/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Uhealth !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/myapp/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
        <form method="post" action="{% url 'myapp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
          <input type="submit" name="" value="Login">
        </form>
      </div>
  </div>
{% endblock %}

templates/myapp/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/myapp/upload.html
{% extends "base.html" %}
{% load static %}


{% block head_block %}
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        <form action="{% url "myapp:upload" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <script type="text/javascript">
            var context = {{context|safe}}
            var error = {{error|safe}}
        </script>

        

        <script src="{% static 'js/image.js' %}"></script>
        <script type="text/javascript">
            //製作圖表
            document.write("<div id=page-wrapper style=margin-left:0> <div class=row>")
            for(num=0 ; num<context.length;num++){
                x = "<div class=col-lg-3>"+
                    "<div class=panel panel-yellow>"+
                    "<div class=panel-body>"+
                    "<div id="+context[num]['title']+" style=height:370px; width:100%;></div>"+
                    "</div>"+
                    "</div>"+
                    "</div>"
                document.write(x);
            }
            document.write("</div> </div>")
            
        </script>
      
        <script type="text/javascript">
            //顯示格式錯誤的欄位
            document.write("<p>"+ error['box_error'] +"</p>");
        </script>

    {% else %}
        <script> document.location.href="{% url 'myapp:user_login' %}";</script>
    {% endif %}
        
{% endblock %}